### ISSUE TITLE
Missing record

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#311]
One or two verifiers have commented that some records seem to have disappeared after review. I've now experienced this with a record I redetted from Oedemera lurida to O. nobilis a few days ago. It was recorded by Peter Smith, he thinks from Cropston, on 16/8/25. I can't find it anywhere so think it may be stuck somewhere..... Please could you check? Thanks.

**Comment by johnvanbreda** [comment]
The record (along with a few others) was stuck in a state which happens after a redetermination, where it is marked as needing an update so not visible in the Elasticsearch outputs (though the record remains in the main database). I don't know why this happened - but re-queueing it for a refresh has fixed the issue with the record. I did the same for all other records in the same state.

**Comment by davidnicholls125** [comment]
We are suddenly seeing records that have previously been redetted reappear without the change nor any record that they have previously been edited - whatever has happened seems to have wiped the history of previous changes. Also, I redetted a couple more records yesterday that haven't appeared on the elasticsearch verification page, though do appear on the old page.

Received this from Mark:

I had record 42669120 that was submitted as Scarlet Tiger that needed to be re-detted as Ruby Tiger – got de ja vu, sure I’ve seen and dealt with this one before. Now I can see record 44604506 as an example – 100% know I done this one before. There are another four or five similar records that I know are not ‘new and unprocessed’ – but the history suggests that.

**Comment by johnvanbreda** [comment]
I'm pretty sure that what has happened here is that these were attempted redeterminations which were processed when the warehouse was having performance problems earlier this year and they actually failed. The records were never successfully redetermined but were "out of sight and out of mind" as they had been flagged for updating in the Elasticsearch data. So in forcing these records to update yesterday they have reappeared in their previous state.

Fortunately the warehouse performance issues have been fixed.

**Comment by davidnicholls125** [comment]
There is still a problem.... records I redetted yesterday have not reappeared on the elasticsearch list. The elasticsearch pending list has 11 beetle records listed whereas the non-elasticsearch list has 20 (including my 'missing' records.

**Comment by johnvanbreda** [comment]
Ok - please can you give me a few records that you would like to redetermine (not the ones you tried yesterday) and the taxa you would like them redetermined to so I can try it myself. Also let me know which browser you used.

**Comment by davidnicholls125** [comment]
OK, but why are there more pending beetle records displaying on the old verification page compared with the equivalent elasticsearch page? I've had to redet both these records (again) from the old page as they don't appear on the elasticsearch page.
43875171: Scaphidium quadrimaculatum, redetted to Nicrophorus investigator
43042621: Leptura quadrifasciata redetted to Leptura aurulenta
Browser - Firefox

**Comment by johnvanbreda** [comment]
Both those records appear in Elasticsearch with the correct determination. What I was after was records that you have never redetermined, but which you are planning to redetermine so I can do it for you and trace exactly what's going on.

Regarding the difference in numbers, these relate to Elasticsearch copies of the records which are stuck in a pending update state due to failed redets - I will fix these all once I've worked out the underling problem.

**Comment by davidnicholls125** [comment]
Sorry if I jumped the gun! 
41565678 - redet to Harpalus rufipes
42626248 - redet to Oedemera lurida
This record is not on elasticsearch and I'm sure has never been redetted (it was submitted with the correct determination) so why is this one not appearing? There may be others but I've not checked them all.

<img width="1167" height="66" alt="Image" src="https://github.com/user-attachments/assets/6015c48c-6155-40bc-bd62-401cebf95bdf" />

**Comment by johnvanbreda** [comment]
Got it - thanks for your help. It was a bug in the option to not update the determiner (which is unique to NatureSpot so not happening elsewhere). The redeterminations were not working - you should have seen an error message to say this?

I've done the first of your 2 examples above to test it.

**Comment by davidnicholls125** [comment]
Thanks. There was an error message but we've had this on and off for years but it didn't appear to have affected the change - though of course it did recently. I'll report it next time!

**Comment by davidnicholls125** [comment]
These two records are still not appearing on elasticsearch.... Do you know why?

<img width="1186" height="192" alt="Image" src="https://github.com/user-attachments/assets/9ffcab16-60ee-4265-8dcf-8f9bd57bf4ca" />

**Comment by johnvanbreda** [comment]
No, I don't know why - I've refreshed them and checked for similar problems in the record IDs either side which there weren't.

**Comment by davidnicholls125** [comment]
They have appeared now, thanks.
