### ISSUE TITLE
Verification page filters timing out

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#32]
The verification page times out when using the filter boxes when 'all records' are in the grid. I've tried entering various terms in several boxes but all time out.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I think the only way to resolve this effectively will be a switch to using the newer Elasticsearch based reporting tools on iRecord. This will unfortunately need some of the amendments we added to the customised NatureSpot version to be redone, but installing the "vanilla" version is a very simple task. We can run both options together for a while, reducing the urgency of recreating these pieces of functionality.

**Comment by davidnicholls125** [comment]
Is the current iRecord version the vanilla set up? It's certainly a much slicker experience!
The key customisation on the NS version is the inclusion of the RAG rating in the grid and the display of RAG + recording advice in the details panel. In addition we would want the NS taxon groups rather than those used by iRecord. Are there others? How much time do you think would be needed?

**Comment by johnvanbreda** [comment]
Yes, the iRecord version is what I'm referring to as "Vanilla". I will just copy the configuration over. The only custom JavaScript on the current NS verification page relates to adding the RAG icon and recording advice. I think I can create the new page, configure to use the NS taxon groups in the grid columns, add the RAG icon and recording advice in about 2 hours. One thing to mention - without further work the "What" panel in the create a filter tool will use the groups from UKSI for filtering, but you can still filter using the NS goups via the row at the top of the records grid.

**Comment by davidnicholls125** [comment]
Thanks John. Go ahead with this please.

**Comment by johnvanbreda** [comment]
https://www.naturespot.org.uk/verification-v2

**Comment by davidnicholls125** [comment]
Looks good! I like the full screen default. 
Can we make the grid wider and the map/details narrower, eg 70:30?
Only four records are on view at a time - the grid window doesn't extend down enough.
The first few records I've tried to verify have given this message and remained on the grid apparently unverified.
![image](https://user-images.githubusercontent.com/80914584/117550051-ef54cf00-b035-11eb-8e92-b3da3431c251.png)

Probably need to use it for a while to get more familiar and see if there is anything else.

**Comment by johnvanbreda** [comment]
I've changed the column widths. I can't reproduce the issue with only 4 records appearing, when I use it on a variety of browsers, the grid bottom is aligned with the page bottom and has a scrollbar for any extra records.

Please can you let me know if there are a few records you don't mind me verifying so I can try to reproduce the error message? E.g. some of yours so I don't have to worry about creating messages and changing the status.

**Comment by davidnicholls125** [comment]
Thanks. The grid window stopped halfway down the screen which was why only four records were visible but it is now the full height.
I've just tried verifying a record and got the same error after I saved the pop up box.:
![image](https://user-images.githubusercontent.com/80914584/117577848-6f853e00-b0e3-11eb-9060-30cb03d0e3d2.png)
You can verify any green rated species record if you are happy it is correct.
Can the map zoom in to the record location when the record is selected? At present it shows the whole of Leicestershire which isn't very helpful.
Is there a way of sorting records by RAG rating?

**Comment by johnvanbreda** [comment]
I've fixed the error, caused by a bit of missing config.

If you double click on a record when you select it, the map will zoom in. If you zoom the map in further, then the map will stay zoomed in to that level as you navigate through the records - the idea being you select the zoom level you like to work at and then the map will stay at that level.

I can't sort by RAG I'm afraid - those values are not part of the information we can store on Elasticsearch.

**Comment by davidnicholls125** [comment]
The log tab button is not on the new version, can this be added?

**Comment by davidnicholls125** [comment]
I've asked all the verifiers to use the new form and send in any feedback.
One report is that when records are verified in bulk they don't disappear from the grid so it isn't clear whether anything has happened. This has led to some records being verified more than once, as illustrated below. It was reported that they do disappear after some delay (a minute or so) or when you move to another page, but it is causing confusion! I've tried it and didn't have this problem but thought I would pass it on. Could it be just the server going slow or perhaps a slow connection?
![image](https://user-images.githubusercontent.com/80914584/119013591-0f1db880-b98f-11eb-9532-8df01e46b49a.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 the log tab is not available using Elasticsearch technology. Although it could be added using the older PostgreSQL queries, when this was discussed with BRC they felt that the performance wasn't very good and that the main purpose of it was just to check what other verifiers have been doing on the records you can verify. You can achieve this by selecting "Decisions by verifiers other than me" in the Status drop down.

I couldn't reproduce the problem with bulk verification. If I bulk verify then after the grid is completely refreshed. Is it possible this is only happening in certain scenarios or on certain browsers? If you can work out any way of reproducing it then it would be helpful.

**Comment by davidnicholls125** [comment]
Thanks John. Another problem is that the recorder experience tab isn't working. It works on iRecord but gives an error message on NS.

I'll ask Sue if she is still getting the error. I suspect it was a glitch when maybe the warehouse server was overworked.

**Comment by davidnicholls125** [comment]
If I click on the recorder experience tab the timer appears but just hangs - and can't be cancelled.
Also we need the NS species list to redetermine a record - currently we only see the iRecord list.

**Comment by johnvanbreda** [comment]
Experience tab fixed, and the redet tool configured to use the NS species list.

**Comment by davidnicholls125** [comment]
Thanks. You will remember that a while ago we 'fixed' the redet tool so it didn't default to enter the redeterminer's name in the 'identified by' field. We need something similar for the new page.

**Comment by davidnicholls125** [comment]
The edit button is bringing up a page not found error.

**Comment by johnvanbreda** [comment]
Edit button now fixed. I still need to do the blocking of the determiner's name going into the identified by field.

**Comment by johnvanbreda** [comment]
Option to prevent overwriting the determiner info has now been added to the redetermination popup dialog. Can this be closed now?

**Comment by davidnicholls125** [comment]
Thanks John.
